deploy: 
 needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.SSH_KEY}}
        script: |
          cd flask-ci-demo || git clone
          https://github.com/renzzomontenegro/flask-ci-demo.git
          cd flask-ci-demo
          git pull
          docker build -t flask-ci-demo .
          docker stop app || true
          docker rm app || true
          docker run -d -p 80:5000 --name app flask-ci-demo
          